apiVersion: v1
kind: Plugin
metadata:
  author: wangling
  name: SchedulerBot
  repository: 'https://github.com/chenpuhao/SchedulerBot'
  version: 1.0.0
  description:
    en_US: Scheduled message plugin for groups and private chats with persistence
    zh_Hans: 群聊/私聊定时消息插件(支持持久化)
  label:
    en_US: SchedulerBot
    zh_Hans: 定时任务机器人

spec:
  config: []
  execution:
    python:
      path: main.py
      attr: SchedulerBotPlugin
